name: Post changelog
on:
    push:
        branches: [master]

jobs:
    post-changelog:
        runs-on: ubuntu-latest
        steps:
            - name: copy reports
              run: cp -R cucumber-messages.ndjson cucumber-report
            - run: cp -R cucumber-report.html cucumber-report
            - name: Upload artifact cucumber-report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-report
                  path: cucumber-*.*
                  retention-days: 5
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: docs
