name: Post changelog
on:
    push:
        branches: [master]

jobs:
    Run_test:
        runs-on: ubuntu-20.04 # Choosing OS
        strategy:
            matrix:
                node-version: [14.17.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            # - name: copy reports
            #   run: cp ./cucumber-messages.ndjson cucumber-report
            - run: ls #cp -r cucumber-report.html cucumber-report
            - name: Upload artifact cucumber-report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-report
                  path: cucumber-*.*
                  retention-days: 5
            - name: Deploy 🚀
              if: always()
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: docs
